services:
  sonarqube:
    image: sonarqube:community
    hostname: sonarqube
    container_name: sonarqube
    env_file:
      - .env
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube_postgresql:5432/sonarqube
      SONAR_JDBC_USERNAME: ${DB_USERNAME}
      SONAR_JDBC_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/sonarqube/data:/opt/sonarqube/data
      - ./data/sonarqube/extensions:/opt/sonarqube/extensions
      - ./data/sonarqube/logs:/opt/sonarqube/logs
    ports:
      - 9000:9000
    restart: unless-stopped

  sonarqube_postgresql:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432