services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CLI_ARGS= #optional
    volumes:
      - ./data:/config
      - /mnt/array/Erebor:/source
    ports:
      - 8200:8200
    restart: unless-stopped
