networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.22.3
    container_name: gitea
    env_file:
      - .env
    environment:
      - GITEA__mailer__ENABLED=false
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./data/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"

  runner:
    image: gitea/act_runner:latest
    env_file:
      - .env
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_RUNNER_NAME: "gitea-runner"
    volumes:
      - ./data/runner/config.yaml:/config.yaml
      - ./data/runner/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
