x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  nightscout_mongo:
    image: mongo:4.4
    volumes:
      # - ${NS_MONGO_DATA_DIR:-./mongo-data}:/data/db:cached
      - ./data:/data/db:cached
    logging: *default-logging
    networks:
      - nightscout-network
    restart: always

  nightscout:
    image: nightscout/cgm-remote-monitor:latest
    container_name: nightscout
    restart: always
    env_file:
      - .env
    depends_on:
      - nightscout_mongo
    ports:
      - '1337:1337'
    logging: *default-logging
    networks:
      - nightscout-network
    environment:
      ### Variables for the container
      NODE_ENV: production
      TZ: Etc/UTC

      ### Overridden variables for Docker Compose setup
      # The `nightscout` service can use HTTP, because we use `traefik` to serve the HTTPS
      # and manage TLS certificates
      # PERSONAL: CLOUDFLARE TUNNEL.
      INSECURE_USE_HTTP: 'true'

      # For all other settings, please refer to the Environment section of the README
      ### Required variables
      # MONGO_CONNECTION - The connection string for your Mongo database.
      # Something like mongodb://sally:sallypass@ds099999.mongolab.com:99999/nightscout
      # The default connects to the `mongo` included in this docker-compose file.
      # If you change it, you probably also want to comment out the entire `mongo` service block
      # and `depends_on` block above.
      MONGO_CONNECTION: mongodb://nightscout_mongo:27017/nightscout

      # API_SECRET - A secret passphrase that must be at least 12 characters long.
      # PERSONAL: DEFINED IN .env FILE.
      # API_SECRET: change_me

      ### Features
      # ENABLE - Used to enable optional features, expects a space delimited list, such as: careportal rawbg iob
      # See https://github.com/nightscout/cgm-remote-monitor#plugins for details
      ENABLE: careportal basal dbsize boluscalc iob cob bwp sage profile rawbg delta direction upbat timeago devicestatus

      # AUTH_DEFAULT_ROLES (readable) - possible values readable, denied, or any valid role name.
      # When readable, anyone can view Nightscout without a token. Setting it to denied will require
      # a token from every visit, using status-only will enable api-secret based login.
      # AUTH_DEFAULT_ROLES: denied
      AUTH_DEFAULT_ROLES: readable

      # For all other settings, please refer to the Environment section of the README
      # https://github.com/nightscout/cgm-remote-monitor#environment

networks:
  nightscout-network:
    driver: bridge
